### ISSUE TITLE
npm install twilio-chat not working

### ISSUE THREAD

**Issue by anurodhsahu** [blackuy/twilio-chat#1]
Hi, when trying to user npm install I am getting below error. Can you plz look into it.

> $ npm install twilio-chat
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected string or string but got null
npm ERR! typeerror     at fetchPackageMetadata (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:36:3)
npm ERR! typeerror     at limited (C:\Program Files\nodejs\node_modules\npm\node_modules\call-limit\call-limit.js:29:10)
npm ERR! typeerror     at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:537:5)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:470:5
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
npm ERR! typeerror     at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:462:3)
npm ERR! typeerror     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
npm ERR! typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
npm ERR! typeerror     at zalgoSafe (C:\Program Files\nodejs\node_modules\npm\node_modules\dezalgo\dezalgo.js:20:10)
npm ERR! typeerror     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anurodh\AppData\Roaming\npm-cache\_logs\2018-06-20T02_13_25_826Z-debug.log

**Comment by bilby91** [comment]
We don't maintain this library any longer. Please install the official version of the SDK.
